const SUPABASE_URL = 'https://sfpqmadsmsmlpjfgmzfx.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_rC3J4lBV55wwD2UOg21eUA_EL1lxGCR';
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id); let mode='login',currentUser=null,profile=null;
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3200)}
function setMode(m){mode=m;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('name-field').classList.toggle('hidden',m==='login');$('confirm-field').classList.toggle('hidden',m==='login');$('forgot-password').classList.toggle('hidden',m!=='login');$('auth-title').textContent=m==='login'?'Bem-vindo de volta':'Crie sua conta';$('auth-subtitle').textContent=m==='login'?'Entre para acessar seu painel.':'Cadastre-se para começar.';$('auth-submit').textContent=m==='login'?'Entrar':'Criar conta'}
async function ensureProfile(u){let {data,error}=await supabase.from('profiles').select('*').eq('id',u.id).maybeSingle();if(error)throw error;if(data)return data;let p={id:u.id,full_name:u.user_metadata?.full_name||u.email?.split('@')[0]||'Usuário',phone:null,role:'user'};let r=await supabase.from('profiles').insert(p).select().single();if(r.error)throw r.error;return r.data}
async function showApp(u){currentUser=u;profile=await ensureProfile(u);$('auth-view').classList.add('hidden');$('app-view').classList.remove('hidden');$('current-user').textContent=u.email||'';$('hello-name').textContent=profile.full_name||'usuário';$('role-badge').textContent=profile.role||'user';$('profile-name').value=profile.full_name||'';$('profile-email').value=u.email||'';$('profile-phone').value=profile.phone||'';const admin=profile.role==='admin';$('admin-panel').classList.toggle('hidden',!admin);if(admin)await loadUsers()}
function esc(v){return String(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
async function loadUsers(){const {data,error}=await supabase.from('profiles').select('id,full_name,role,created_at').order('created_at',{ascending:false});if(error)return toast(error.message);$('users-body').innerHTML=(data||[]).map(u=>`<tr><td>${esc(u.full_name||'—')}</td><td>${u.id===currentUser.id?esc(currentUser.email||''):'••••••••'}</td><td><span class="badge">${esc(u.role||'user')}</span></td><td class="status">Ativo</td></tr>`).join('')||'<tr><td colspan="4">Nenhum usuário.</td></tr>'}
$('auth-form').addEventListener('submit',async e=>{e.preventDefault();const email=$('email').value.trim(),password=$('password').value;try{if(mode==='register'){const name=$('name').value.trim();if(password!==$('confirm-password').value)throw Error('As senhas não coincidem.');const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)throw error;if(data.session)await showApp(data.user);else toast('Conta criada. Verifique seu e-mail para confirmar o cadastro.')}else{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;await showApp(data.user)}}catch(err){toast(err.message||'Não foi possível concluir a operação.')}});
$('forgot-password').addEventListener('click',async()=>{const email=$('email').value.trim();if(!email)return toast('Informe seu e-mail primeiro.');const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});toast(error?error.message:'Link de recuperação enviado para seu e-mail.')});
$('profile-form').addEventListener('submit',async e=>{e.preventDefault();const full_name=$('profile-name').value.trim(),phone=$('profile-phone').value.trim();const {data,error}=await supabase.from('profiles').update({full_name,phone}).eq('id',currentUser.id).select().single();if(error)return toast(error.message);profile=data;$('hello-name').textContent=full_name||'usuário';toast('Perfil atualizado com sucesso.')});
$('password-form').addEventListener('submit',async e=>{e.preventDefault();const password=$('new-password').value;if(password!==$('new-password-confirm').value)return toast('As senhas não coincidem.');const {error}=await supabase.auth.updateUser({password});if(error)return toast(error.message);e.target.reset();toast('Senha alterada com sucesso.')});
$('logout').addEventListener('click',async()=>{await supabase.auth.signOut();location.reload()});$('refresh-users').addEventListener('click',loadUsers);document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));supabase.auth.onAuthStateChange(async(_,s)=>{if(s&&!currentUser)try{await showApp(s.user)}catch(e){toast(e.message)}});(async()=>{const {data}=await supabase.auth.getSession();if(data.session)try{await showApp(data.session.user)}catch(e){toast(e.message)}})();
